Models/ErrorViewModel.cs
namespace MVCHomework6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCHomework6.Models;
using System.Diagnostics;
using MVCHomework6.Data;
using MVCHomework6.Data.Database;
using X.PagedList;
using System.Linq;

namespace MVCHomework6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly BlogDbContext _context;
        private int pageSize = 5;

        public HomeController(ILogger<HomeController> logger, BlogDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int page)
        {
            page = (page == 0) ? 1 : page;
            var model = _context.Articles.ToPagedList(page, pageSize);

            return View(model);
        }

        [HttpGet]
        public IActionResult FindSearch(string SearchString, int page)
        {
            page = (page == 0) ? 1 : page;

            if (SearchString == null)
            {
                var AllArticles = _context.Articles.ToPagedList(1, pageSize); ;
                return View(AllArticles);
            }

            var Searchresult = _context.Articles.Where(x => x.Body.Contains(SearchString));
            var model = Searchresult.ToPagedList(page, pageSize);

            ViewData["SearchContext"] = $"{SearchString}";
            return View(model);
        }

        [Route("FindTag/{tag?}/{page?}")]
        public IActionResult FindTag(string tag, int page)
        {
            page = (page == 0) ? 1 : page;

            var SearchTag = from item in _context.Articles.AsEnumerable()
                            where item.Tags.Split(",").Contains(tag)
                            select item;

            var model = SearchTag.ToPagedList(page, pageSize);

            ViewData["tag"] = $"{tag}";

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewComponets/TagColudViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCHomework6.Data.Database;

namespace MVCHomework6.ViewComponets
{
    public class TagColudViewComponent : ViewComponent
    {
        private readonly BlogDbContext _context;

        public TagColudViewComponent(BlogDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var source = _context.TagCloud;
            ViewData.Model = source;
            return View();
        }
    }
}

Views/Home/FindSearch.cshtml
@model IEnumerable<MVCHomework6.Data.Database.Articles>
@using X.PagedList;
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Core
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "FindSearch";
}

<partial name="_Articles" model="Model">
 
 @Html.PagedListPager((IPagedList)Model,x=> Url.Action("FindSearch",new { SearchString=@ViewData["SearchContext"],page= x }))

Views/Home/FindTag.cshtml
@model IEnumerable<MVCHomework6.Data.Database.Articles>
@using X.PagedList;
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Core
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "FindTag";
}

 <partial name="_Articles" model="Model">
 
 @Html.PagedListPager((IPagedList)Model,x=> Url.Action("FindTag",new { tag=@ViewData["tag"],page= x }))

Views/Home/Index.cshtml
@model IEnumerable<MVCHomework6.Data.Database.Articles>
@using X.PagedList;
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Home Page";
}

<partial name="_Articles" model="Model">
 
@Html.PagedListPager((IPagedList)Model,x=> Url.Action("Index",new { page= x }))

Views/Shared/Components/TagColud/Default.cshtml
@model IEnumerable<MVCHomework6.Data.Database.TagCloud>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    foreach (var item in Model)
    {
        <a asp-controller="Home" asp-action="FindTag" asp-route-tag="@item.Name">@item.Name (@item.Amount)</a>
    }

}

Views/Shared/_Articles.cshtml
@model IEnumerable<MVCHomework6.Data.Database.Articles>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
      foreach(var item in Model)
    {
        <div class="card mb-4">
            <img class="card-img-top" src="@item.CoverPhoto" alt="@item.Title">
                <div class="card-body">
                    <h2 class="card-title">@item.Title</h2>
                    <p class="card-text">@Html.Raw(item.Body)</p>           
                    <tags>@item.Tags</tags>                                                                
                </div>
         </div>
         <div class="card-footer text-muted">   
              Posted on @item.CreateDate.ToString("yyyy-MM-dd") by me
         </div>
    }
    
    
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCHomework6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCHomework6.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCHomework6</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <div class="row">
        <div class="col-8">
            @RenderBody()
        </div>
        <div class="col">
            <div class="card mb-1">
                <div class="card-header">
                    Search
                </div>
                <div class="card-body">
                     <form  method="get" asp-action="FindSearch">
                          <div class="input-group mb-3">
                              <input  name="SearchString" class="form-control" value="@ViewData["SearchContext"]" placeholder="Search for...">                                                                                                
                              <button type="submit" class="btn btn-primary" >Go!</button>
                          </div>
                     </form>
                 </div>
            </div>
            <div class="card mb-1"  >
                <div class="card-header" >
                    Tags
                </div>
                <div class="card-body">  
                    <vc:tag-colud></vc:tag-colud>            
                </div>
            </div>
            <div class="card mb-1">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCHomework6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>